// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxtzfvvswfugekfileis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4dHpmdnZzd2Z1Z2VrZmlsZWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDMwMzksImV4cCI6MjA2NzI3OTAzOX0.O7-Z9a-wZ8NvWmidfioLsZNVRs2pywnly8lArVJYeEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});